data = [
    {
        "title": "Adaptive Allotropy",
        "Summary": "Adaptive Allotropy made their first breakthough in transparent silicon bucky-structures in the late 2030s. Fortunately unmanned test mission saw these windows explode after a mere 6 minutes in Low earth orbit, and led to a further 6 years of painstaking research before their certification of mission use. ",
        "Details": "Adaptive Allotropy supplies windows made from silicon bucky-structures materials for use on space settlements. Windows can be ordered in any shape. With proper sealing, standard, 12 mm thick, windows with rectangular side length or diameter no greater than 0.91 m can retain up to a 1.01 bar pressure difference across them.The allowable safe span doubles if the thickness of the window is doubled, while the allowable pressure difference squares with the increase in thickness (e.g. doubling the thickness allows for four times the pressure difference)*. If never exposed to direct sunlight, windows provide adequate radiation and thermal insulation, they are, however, prone to brittle failure.The price per unit is $1,000 per m3 of material, multiplied by the thickness in mm. For bulk orders, Adaptive Allotropy will offer reductions from the list price: 1-10, 0%; 10-50, 5%; 50-100, 10%; 100-200, 15%; 200-400, 20%; 400-1,000, 25%; 1,000-2,000, 30%; 2,000-10,000, 35%; >10,000, 40%. Costs are rounded up on each unit to the nearest $0.01. This price does not include shipping from Bellevistat.*This is quantified with the equation \u03c3max = (\u0394p L2) / (2 t2) where \u0394p is the pressure difference in Pa, L is the span in m, t is the thickness in m, and \u03c3max is the maximum allowable tensile stress in the material, 290.1 MPa. "
    },
    {
        "title": "Advanced Materials Group (AdMaG)",
        "Summary": "Advanced Materials Group (AdMaG) are the industry leaders in the supply of specialist plastics, composites, and aerogels. They operate from locations throughout the solar system. ",
        "Details": "AdMaG produces unformed bulk material to customers\u2019 or their own specifications. Their own products include a transparent PMMA equivalent with a working temperature up to 675 K (this can be used in windows by applying the formula from Adaptive Allotropy with a \u03c3max of 70 MPa), and a space rated carbon-nanotube-mesh reinforced polycarbonate with a maximum temperature of 500 K and a yield strength of 130 MPa. These materials have densities of 1,190 kgm-3 and 1,240 kgm-3 and prices of $1.60 per kg and $0.85 per kg respectively.AdMaG regularly produces specialist orders to customer specifications at their sites around the solar system. They can source materials themselves, charging the market rate for materials plus $0.05 per kg sourced and shipping costs of said materials, or receive materials directly from the customer. They charge $7.50 per kg of material produced to customer specifications, with a minimum contract size of 5 tonnes of material. Specialist orders of structured composites are produced formed with an added fee of $5 per kg.AdMaG sells silica, carbon, and alumina aerogels at a price of only $2,000 per kg. These are produced on-site with specialist equipment. The transport of the equipment and raw stock is included in the price of the material, but a minimum order size of 30 kg is in place. This aerogel is increasingly being used as a filler material between the layers of Whipple shield panel.AdMaG processes their plastics, composites, and aerogels at Liberty, a Martian Mining Settlement, and Arial respectively.AdMaG are the sole manufacturers and distributors of Flusshalt-X, a polymer-based radiation shielding material designed by Kepler Automation. This material is available in 1o mm thick panels or can be formed like any other thermoplastic as required. As a rule of thumb, it has five times the linear attenuation coefficient of steel against all types of radiation. It has a density of 1,200 kgm-3 and is priced at $70 per kg.\u00a0Corporate Links:In return for licensing their Flusshalt-X radiation shielding material to AdMaG, Kepler are able to claim significant discounts on it and other products manufactured by AdMaG. For Foundation Society contracts, this discount is limited to 20%. "
    },
    {
        "title": "Applied Carbon",
        "Summary": "Applied Carbon was established by a group of materials science students whilst on their foreign placement year at the Liberty space station after they discovered a new treatment for waste carbonaceous material. A short crowdfunding campaign allowed them to raise the money needed to purchase a small workshop on Liberty, from which they have expanded to become a major player in the environmentally friendly production of plastics. ",
        "Details": "Applied Carbon is an independent supplier of plastics based out of Liberty. Their products are completely sourced from reprocessed waste carbonaceous material and as such generally have only 90% of the value of the property of the plastic they seek to emulate. The price of the material is generally 70% of the price of the new material, not including shipping. Plastics are available as sheets, extruded beams or pellets for injection moulding. They will buy waste structured carbon (e.g. wheat sheaves) delivered to them for $2.50 per kg. "
    },
    {
        "title": "Crucible Ltd.",
        "Summary": "Crucible, Ltd. is a Sheffield-based company which operates an automated manufacturing facility on the Amor group ferro-nickel asteroid (6178) 1986 DA. Whilst limited assembly is possible on site, the company strongly reccomends no people are left on the asteroid during its almost 2 year journey out to its aphelion as they are likely to suffer from loneliness and isolation issues. ",
        "Details": "The company produces triangular trusses (usually in a Warren girder) and sheets to customer-specified dimensions, at a rate of 2,500 kg of beam per hour. Some limited assembly of products is permitted in the vicinity of this operation (space rented on the asteroid\u2019s surface or within 10 km at a rate of $500 per day) but customers are required to organise transportation themselves, with the most common destinations being the orbits of Bellevistat and Aresam, having delta-V\u2019s of 1.20 kms-1 and 1.14 kms-1 respectively.Crucible Ltd. charges $0.20 per kilogram of formed metal or $0.10 per kg of metal provided as 5 mm diameter spheres. The metals offered are: iron (steel), nickel, chromium, cobalt, copper, lead, molybdenum, manganese, magnesium, silver, zinc, zirconium, and alloys of any of these metals (surcharge of $0.10 per kg). Available unformed only at a higher price of $1.20 per kg are bismuth, calcium, gold, iridium, osmium, palladium, platinum, rhenium, rhodium, ruthenium, tantalum, tungsten. Crucible will pay clients $0.05 per kg to rid them of slag, consisting of 98% fused silicon dioxide by mass, and 2% trace metal oxides. "
    },
    {
        "title": "earhart skunkworks",
        "Summary": "Earhart Skunkworks is the materials research and development arm of EAI. As an owned entity, they are subject to the 20% reduction rule for Foundation Society contracts. AS such, EAI may use EAI Skunkworks products at 80% of the listed price. ",
        "Details": "EAI-Skunkworks\u2019 primary product is a soft-magnetic titanium alloy. The material achieves a yield strength of 1250 MPa, and an ultimate tensile strength of 2000 MPa at standard conditions. These strengths halve every 600 degrees, up to its melting point of 2023 K. The density and other mechanical properties are equivalent to other high-performance titanium alloys. The excellent thermal performance is believed to be due to the formation of a solid solutions of nickel within the metal structure, although the exact chemical composition is clearly a trade-secret! However, you can purchase this material for only $40/kg from EAI-Skunkworks for use in all your space related applications. "
    },
    {
        "title": "Orbital Foundry",
        "Summary": "Orbital Foundry was originally part of a major Canadian aerospace conglomerate, but was bought out by CEO and Spanish billionaire Isabella Gonz\u00e1lez during the construction of Bellevistat in order to capitalise on the growth in stock value. The company was a major provider for the Foundation Society in that project and has since been involved in almost every mega-project. ",
        "Details": "Orbital Foundry accepts ores from off world mining operations, refines the metals and produces rolled sheets, extruded beams and custom shaped parts manufactured by cutting or turning processes.Orbital Foundry is capable of a throughput of 2,000 kg of product per hour, charging $0.15 per kg of ore given and processed through them or $0.20 per kg directly bought. They have processing facilities on Earth, Bellevistat, and Alaskol. They will not pay for shipping of products or stock for customers. "
    },
    {
        "title": "Out of the Woods",
        "Summary": "Having grown up in the rainforests of Borneo, founder Dinihari binti Osman repeatedly stresses the virtues of design involving wood, inciting the calming and homely feel it creates, something that when she first set foot on Balderol she felt was sorely missing.  ",
        "Details": "Out of the Woods is a small organisation that operates one of only a handful of off-world tree farms. They are based at Balderol and produce their wood as by product from their main task of CO2 removal. They sell a huge variety of wood from Oak to Purple Heart cut into regular sizes for an average of $500 per cubic metre. However, their manufacturing capacity is limited to 8 tonnes of exports a year. "
    },
    {
        "title": "Sealant Advancements",
        "Summary": "Established by an American chemist, Sealant advancements was born out of a chemical experiment that initially showed little promise of producing any desirable products. However after being left forgotten in the back of a fume cupboard, Luke Johnson returned to find a transparent layer of solid material, underneath which a gas bubble couple be seen. Further investigation into this material showed it to be an excellent sealant to prevent gas leaks, although it did not have the strength to contain pressures above 100Pa. ",
        "Details": "\t\t\t\tSealant Advancements makes paint and coatings from near-Earth asteroid mined materials that provide air-tight surfaces on rock, SuperAdobe and other porous surfaces. Application is done with standard paintbrushes or aerosols and the surface requires 30 Earth days to dry before being capable of retaining air. These are produced at Bellevistat where the company holds a stock of 50,000 litres priced at $55 per litre. To be effective the paint requires a coating thickness of 0.5 mm and it has a density of 2,000 kgm-3. An indefinitely sized layer of the coating can only bear a pressure difference of 100 Pa when unsupported.\t\t\t\t\t"
    },
    {
        "title": "Tubular Technologies",
        "Summary": "Founder and CEO Jack Brown may not be the most modest man and will always be the first to remind you that for carbon nanotubes, the length of the product plays a critical role defining its possible applications. He regularly likes to publicly point out that his company has achieved tube lengths double those produced by any of their competition. Despite this lack of modesty, it is undeniable that the rapid advancements of Tubular Technologies in productions of catalysts for creation of carbon fibre has allowed for far wider applications of the material on scales that were hard to imagine only 20 years ag ",
        "Details": "Tubular Technologies, based on Alexandriat, is the industry-leading producer of carbon nanotubes for industrial and scientific uses, for both space-based and customers on Earth. The company has succeeded in making nanotube cross-linked strings up to 2 km long, although most applications are in the one to ten foot range. Nanotubes add strength to conventional materials; primary customers are manufacturers of construction elements (e.g. for buildings and bridges) and components for machinery, vehicles and tools.Although the company is vigorously pursuing techniques to produce longer nanotubes, it is not yet able to achieve the 1,000-mile lengths required to build a cable that would withstand the tensile loads of a space elevator to Earth\u2019s surface. However, given the experience the company gained from working on both the Arial settlement and OMTC Nix, it is only a matter of time before they fulfil their vision of an Earth-based space elevator!Nanotubes are sold in 0.2mm diameter cables for a price given by $(5 * (length2)). "
    },
    {
        "title": "3D Logistics",
        "Summary": "3D Logistics is a multinational corporation that leads in additive manufacturing technologies, with their main off-world production facility based out of Alexandriat. The company provides both printed components and complete 3D printing systems for purchase.  ",
        "Details": "They are able to produce metal, plastic and ceramic components with an accuracy of 30 microns up to 8 x 4 x 4 metres in sizes with their in-house proprietary systems, while systems on sale are capable of 40 micron accuracy within a volume of 5 x 2.5 x 2.5 metres ($750,000). Their mobile printer designs can achieve 3,000 micron accuracies laying at 0.5 litres per second in an unlimited volume of simple metals and plastics with a power requirement of 60 kW for $500,000. The high precision systems consume 50 kW to lay 0.5 litres of material per 20 seconds. This material is laid across the entire surface before laser sintering. The time to produce a part is hence given by the height of the part in millimetres multiplied by 500 to give the time in seconds. This formula can also be applied to the purchased high precision machines. 3D Logistics will charge per second for use of their in-house machines ($0.05, $0.20, and $0.40 for plastics, metals, and ceramics respectively). "
    },
    {
        "title": "Inflatable Innovations",
        "Summary": "Established in the late 2020s by an entrepreneurial Australian balloon artist, Inflatable Innovations capitalised on the space boom of the early 2030s to establish itself as the leading manufacturer of inflatable space habitats. ",
        "Details": "Inflatable Innovations specialises in making inflatable buildings to customer specifications, to enable quick construction of new communities. Although these structures are not intended for permanent or indefinite use, they provide shelter for residents to start new economic activities, until more durable solutions can be established. They are manufactured at Bellevistat for the customer\u2019s collection. The company charges for construction of inflatable facilities at a rate determined by cost = 15,000 + (600*V), where V is the enclosed volume in m3. The shelters provide no protection against radiation but are 90% thermally insulative. "
    },
    {
        "title": "Digg",
        "Summary": "Digg are the pioneers of off-world excavation. Named after their founder Douglas Digg, the company has adapted designs of terrestrial excavation equipment for use in low-g environments. ",
        "Details": "They have created mining equipment, trench diggers, backhoes, dirt-movers, graders, drills and tunnelers and will create new machines on request. Some types of applications require more than one design solution depending on whether local conditions enable bracing the equipment to compensate for lack of gravity.Contracts have call out and services costs in order to place equipment at location and to perform the required task. This price is given by the delta-v (in ms-1) from their head-quarters at Freedom to the location multiplied by the gravitational field strength of the location (in ms-2), rounded up to one significant figure, multiplied by the volume of material to be removed (m3) multiplied by ten.Example calculation: 1000 m3 to be removed on Mars. Delta-v to Mars from LEO is 3,600 ms-1 while the gravitational field strength is 3.711 ms-2. Rounding up the field strength gives 4 ms-2 to yield a final calculation of cost = 10 * 3,600 * 4 * 1,000 = $144,000,000. "
    },
    {
        "title": "Dirtbuilders",
        "Summary": "Superadobe provides an excellent manufacturing material. Construction simply requires uisng compacted earth in sandbags, built around a wire frame and covered in plaster, yet it produces buildings that are resistant to earthquakes! Dirtbuilders is a combined service by multiple, small, Earth-based companies who offer expertise and long term improvements on Superadobe lunar and Martian structures. They have done research allowing the use of martian and lunar soil in their Superadobe, minimising transport costs. Moreover, recent developments in 3D printing technology of Superadobe allow for rapid home construction with excellent thermal insulation properties. ",
        "Details": "They offer mixing agents for superadobe to make it set with exposure to other chemicals within five seconds, rather than by evaporation of moisture while also doubling the shear strength of the material. This allows more abrupt overhangs to be built into designs.In Lunar gravity, default SuperAdobe structures can be built up to 21 metres high and 15 metres in diameter. The height may be multiplied by 1.5 for chemically modified material or doubled if the diameter is multiplied by 1.5 times. Dirtbuilders recommend usage of this product with Large Print mobile printers. They also offer an alternative tool head for 3D Logistics/Large Print mobile printers which can apply continuous fibres into the superadobe or apply a stitched layer of material along the outer or inner surfaces of the printed structure*. The fibres/fabric must be sourced elsewhere.The additive is sold for $2,000 per kg, has a density of 2,000 kgm-3, and should be mixed in a ratio of 1:16 with superadobe mixture by volume. The print heads run to $12,000 per unit.* The strength of the fibre/fabric reinforced superadobe along the fibre direction may be calculated by the mixture rule (XC = Xf Vf + Xm (1 \u2013 Vf)), where Vf is the fibre volume fraction, and XC, Xf and Xm are the properties of the composite, fibre and matrix respectively). "
    },
    {
        "title": "Large Print",
        "Summary": "Large Print was founded in the early 2030s when the founder Michelle Langer started to notice a build up in the number of old 3D printing robots. Large Print buy these robots and adapt them to be able to print on Lunar and Martian surfaces. ",
        "Details": "Their mobile printer designs are capable of operating in a vacuum and can achieve 10 mm accuracies as they deposit Superadobe at a rate of 1 litre per second. Their print volume is unrestricted.Each unit costs $450,000 and is supplied from Alaskol. "
    },
    {
        "title": "LightWorks",
        "Summary": "Following the famous Japanese Blackout during the September 2035 total eclipse, CEO Light Amahara realised that the reliance of the world on solar power had resulted in a major gap in the market. This led to the foundation of LightWorks which provides soletta and lunette illumination for lunar and terrestrial surface locations.  ",
        "Details": "The company provides huge orbiting structures that reflect sunlight during the night or during eclipses. The devices consist of sodium-coated fabric made from lunar materials stretched over lightweight composite structures and are constructed in 4,000 km lunar orbits. Six lunettas (each 1 km2, each cost $120,000,000) enable ground-based solar power plants to operate all night.Lightworks has also purchased the Solaris constellation from Da Vinci Meccanica, which is a constellation of 24 satellites orbiting in Medium Earth Orbit. These satellites are able to transfer power to microwave rectanna within 450,000km of their orbit, as long as they have a clear line of site, as the exceptionally low price of $100,000 per GWh.\u00a0 "
    },
    {
        "title": "Magnetic Propulsion Union",
        "Summary": "Magnetic Propulsion Union (MPU) was founded by three professors at Princeton who continued work with mass drivers originally started by Gerard O\u2019Neill. The MPU has spiraled out into a large international project, encompassing many universities and voluntary projects. They exist as a large repository of knowledge and idealism; with constantly improving designs, in terms of launch mass, efficiency or reliability. ",
        "Details": "\t\t\t\tMPU offer to build mass drivers with a muzzle momentum of up 120,000 kgms-1. The price of such a system is based on the length of the mass driver, costing $50,000,000 per kilometer, and massing in at 98,000,000 kg per kilometre. The mass driver will impart 6000 kgms-1 per kilometre of length. Shipping is not included.The mass driver transfers energy to projectiles with a 60% efficiency.\t\t\t\t\t"
    },
    {
        "title": "Planetary Pavers",
        "Summary": "It was always clear that roads in space would have to be constructed in a different way to those on earth. Launching the required, dense material into space simply could not be done in an economical way. Thankfully Planetary pavers forsaw this problem and began research in the mid 2020s into grading, paving and sintering machinery that could work in space. As their founder says \u2018No matter where you are in the solar system, you can always count on the fact that at some point you will need to be somewhere else!\u2019 Planetary pavers strive to make those journeys as easy and comfortable as possible for you. ",
        "Details": "\u201cPlanetary Pavers operates customised autonomous road-building equipment on off-world settlements. The company\u2019s grading and paving machinery is solar powered with 14 Earth days of battery life for operation in darkness. Their capabilities include breaking rock to make gravel and sintering regolith to create a hard and smooth road surface. After a surface is levelled about 1km of paved surface can be completed every 24 hours.Pricing is done based on the width of the road and the time taken for project completion. An initial contracting fee of $15,000,000 is levied followed by $1,000,000 per 20 metres width, rounded up, per day.\u201d "
    },
    {
        "title": "Progressive Plumbing",
        "Summary": "Whilst it may not be the most appealing design challenge to some, Bog Bazelgette noticed the gap in the market for low-g sewage systems. Following in his great great grandfather\u2019s footsteps, Bog has led Progressive Plumbing to corner this niche market with their novel peristaltic design. ",
        "Details": "Progressive Plumbing has developed peristaltic sewerage systems that are less prone to jamming, do not require high pressure to operate, and operate in zero-g conditions. Silicone spheres with the same outer diameter as the pipe are used to provide a surface for the electro-hydraulic bladders to press against to move the waste stream. Provision must be made for these spheres at intersections or terminuses with processing equipment. The spheres must move through a loop or have separate systems in place for moving them back through the system and must be cleaned after 96 hours in operation for hygiene purposes. The peristaltic effect may operate in both directions along the pipe.The sewers have a power drain of 1W per kg to be moved per second. The waste maxes out at a speed of 1 ms-1 in the 0.5 m diameter pipes. The probability of a single failure in a system of length x metres is x * 0.0001 and hence multiple failures are distributed Poissonially. Progressive Plumbing charge a flat contract fee of $1,000,000 per installation with a cost of $50 per metre of piping. This includes supervision of installation but does not include shipping of the material to the site. The system will be guaranteed for 5 years after the completion of installation. The pipe weighs 1.5 kg per metre while each sphere weighs 11.3 kg and both are produced in Nebraska. "
    },
    {
        "title": "STARRS",
        "Summary": "STARRS In 2024, following the severe damage to the ISS in a collision with a piece of space junk, Da Vinci Meccanica realised the need for a dedicated space debris removal system to protect major space assets from dangers of Kessler Syndrome. And thus STARRS was born. Standing for Space Trash Automated Retrieval and Repurposing System, we used our expertise in waste product recycling to convert much of the former space junk into materials for use in construction. ",
        "Details": "Should you wish to purchase a STARRS system to protect your space assets, prices start at $500,000 for protection of a satellite under 1m^3 and the price scales with the square root of structure volume for our basic service. which will remove any debris with a major length over 10cm from your orbit. For removal of debris down to a size of 5mm, you may purchase SSTARRS (Small Space Trash Automated Removal and Repurposing System) cover, which for only 1.8 times the cost of our basic cover, will help to keep your assets safe from those hand grenade like pieces of small space junk! "
    },
    {
        "title": "Bots4U",
        "Summary": "Originally a firm of injury lawyers, Bots4U gathered data to support a workplace robot marketing campaign. They designed robots to handle typical injury inducing activities such as moving furniture and used their data to convince companies that it was an essential investment in order to protect their employeees. Whilst its seems counterintuitive for an injury lawyer firm to prevent injuries, they knew the value of the market and the business skyrocketed within the first 2 years of the release of their first bot. This provided them with the R&D budget required to invest into design of home use robots, which is now their main source of revenue. ",
        "Details": "Bots4U offers purpose-built robots for home and office use only. Currently available functions for robots are cleaning household surfaces, washing dishes, doing laundry, moving furniture and fetching household items for their owners.The company offers to build robots to customer specification and constructs them at their plant at Alexandriat. The company charges a $10,000 deposit per currently available function, and then $700 per unit produced. The company may be willing to look into new functions provided that the Research and Development costs of $10,000,000 per function are covered by the customer, as well as increasing the cost per unit to $1200. "
    },
    {
        "title": "Distributed Power Systems",
        "Summary": "As with all space technology, Distributed Power Systems noticed that there would be a great reduction in transport costs if they moved their manufacturing processes off earth, and so quickly secured themselves a place on the Alexandriat settlement. They have used near earth asteroid mining to source necessary materials and have therefore been able to produce products at very affordable prices. ",
        "Details": "Distributed Power Systems is the leading supplier of wire harnesses for distribution of electrical power, and fibre optics for electronic signals on spacecraft, manufacturing them for traditional prices at Alexandriat.The company\u2019s latest venture is a system for zero-g manufacturing of solar cells from materials available in silicate asteroids. Distributed Power Systems sells each of these units, which can be transported as an 8 CASSSC block, for $80,000,000, not including transportation to deposit it on an appropriate asteroid where it produces square 0.5 m solar panels at the rate of 100 per day, each of which is capable of 38% efficiency and weighs 1 kg. "
    },
    {
        "title": "ElectroProtect",
        "Summary": "With the rapid expansion into space infrastructure, it was clear that a specialised manufacturer was needed to deal with the vast quantity of eletronic shielding required for space operations. ElectroProtect started out as a Harvard spin-out company, but as the demand for their product increased, they have grown into a major player in the space game. ",
        "Details": "ElectroProtect build components for circuitry that can withstand space environments and shielding or protective boxes for components and circuits that cannot be built to withstand local environments.ElectroProtect stock components run at the same price as the unprotected variants while custom hardware runs at approximately twice the price as unprotected equipment. ElectroProtect charges a yearly membership fee of $400,000 for access to its services and shipping is not included from its Bellevistat manufacturing facility.\u00a0Corporate Links:\u00a0Thanks to the licencing of Flussmitteldurchl\u00e4ssig-VII to ElectroProtect by Kepler Automation, giving the former a significant market advantage, Kepler Automation is offered significant discounts by ElectroProtect. Due to Foundation Society Rules, Kepler may only quote a 20% reduction in the price of ElectroProtect products due to this link. "
    },
    {
        "title": "Fission Frontiers",
        "Summary": "Fission Frontiers grew out of a number of Earth-based small modular reactor companies who merged in the early 2030\u2019s in order to simplify international reactor safety-case approval procedures. This allowed the adoption of fission power to increase as nations strove to meet their climate change targets. ",
        "Details": "Fission Frontiers operates as both a modular reactor seller and a design contractor for reactor design. While they sell thermal-neutron-spectrum reactors for the terrestrial market, the promote fast reactors for off-world applications: they claim that the longer servicing periods, lower waste production, and higher power densities are ideal for space settlements.Available as off-the-shelf units, Fission Frontiers sell modular reactors with the following names and specifications:Tarasque: Molten-salt cooled, pebble-bed, thermal, uranium fuelled VHTR producing 1 GWt at an outlet temperature of 1300 K: $1,900,000,000; 1,100,000 kgGuivre: Lead cooled, fuel rod, uranium fuelled fast breeder reactor, producing 2 GWt at an outlet temperature of 1100 K: $1,200,000,000; 2,000,000 kgPeluda: Forced convection, fuel rod, thermal, uranium fuelled PWR producing 1 GWt at an outlet temperature of 600 K: $900,000,000; 740,000 kgLindworm: Molten-salt cooled, pebble-bed, thermal spectrum LFTR (thorium cycle) producing 500 MWt at 950 K: $1,500,000,000; 1,140,000 kgWyvern: Natural convection, fuel rod, thermal, uranium fuelled LWR producing 250 MWt at 600 K; $300,000,000; 720,000 kgFission Frontiers pride themselves on rising to any design challenge when it comes to reactors, however such projects are expensive due to the demands to reactor safety-case approval. Consultation is required for the provision of a quote.The electrical generation must be performed using a Rankine cycle, however the choice of working fluid is left to the customer (it must be liquid at the operating temperature but can be at any pressure), as well as any bottoming cycles. It is acceptable to assume that the working fluid will reach 10 degrees lower than reactor outlet temperature. It is acceptable for design calculations utilising a generic Rankine cycle to assume that it achieves 0.7 * \u03b7c, where \u03b7c is the Carnot efficiency of the power-extraction, between the maximum working fluid temperature, and the temperature of the heat sink. "
    },
    {
        "title": "Fusion Founders",
        "Summary": "Fusion Founders serendipitously happened upon an apparently ideal combination of conditions and equipment to produce practical fusion power in 2032. This process has remained a very tightly guarded secret, and as such this company has remained the sole provider in this lucrative market, despite the best efforts of other companies.  ",
        "Details": "Although Fusion Founders can assemble large municipal power plants at customer-specified sites, its most popular product is a self contained unit that can be shipped in a modified version of a C-18 transport aircraft, and installed by local labour with supervision of a company engineer.The unit, weighing 90.8 tonnes, includes a 5.2 metre diameter sphere, it\u2019s 24.4 metre long turbine \u2018barn\u2019 and support \u2018shed\u2019. The system is shipped pre assembled and generates a heat output of 300 MWt. The plant operates at an efficiency of 70% of the Carnot efficiency. The maximum temperature of the effective hot reservoir is 1,300K. The cost of such a unit excluding heat dissipation systems is $600,000,000. The reactor must be shut down every 1,200 hours for maintenance of the containment chamber (requires plating replacement every other maintenance period on average) and to refurbish the cermet turbine blades. The reactor containment requires a constant power input of 5 MW while running and 6MW during the 1 hour start-up period.Fusion Founders require a full schematic and report of cooling measures before agreeing to install, for legal liability reasons. "
    },
    {
        "title": "StarDream",
        "Summary": "StarDream StarDream is a product by Kepler Automation, entitling them to quote a 20% lower cost to the Foundation Society. ",
        "Details": "StarDream is a software package for seamless human-machine interfacing: it provides voice, gesture, and body language recognition. It provides 2.4x greater intention-recognition than its nearest competitor. Development APIs for Python 4.1+, C++29, Rust 2.56, Gyst, and Embedded C, are available to implemented StarDream into pre-existing hardware setups. Kepler also sell detection modules that are sufficient to receive commands in a 10 by 10 metre room (assuming a ceiling height of less than 3 metres), so long as there are no interruptions in the sight-line to the user.StarDream Domestic is licensed per point of detection at a cost of $400 per annum. The detection module is priced at $600 and includes a domestic license for one year. StarDream Commercial is licensed at $500 per detection location per annum and is intended for business settings, such as offices, shops, etc. StarDream Industrial is the most advanced and capable package and is licensed per user (for safety) at a cost of $1,000 per annum. "
    },
    {
        "title": "Nano Solutions",
        "Summary": "The combination of the continued shrinking of technology alongside new manufacturing techniques in zero-g and vacuum conditions have allowed Nano Solutions to commercialise\u00a0and market production of programmed nanobots. The company is constantly innovating new nanobot applications, and accepts challenges to design for custom uses.  ",
        "Details": "Programmed nanobots sell by the troy ounce (31.10 grammes) at roughly 10 times the cost of platinum (~$10,500), when delivered they resemble a fine powder the customer applies as a thin layer to the working surface. Service life is one to five Earth years, depending on operating environment and application. In a hard radiation environment such as space, the nanobots have been found to have a half-life of 1 year.Nano Solutions reprograms nanobots for new tasks (compatible with their original application) for a modest fee. Consultation about the capabilities of the nanobots is required prior to commissioning, however Nano Solutions has committed to a cost of $8,000 per task to be known by each troy ounce of nanobots.\u00a0Corporate Links:For applications regarding construction using nanobots, due to previous research contributions, EAI has negotiated a 20% reduction in purchase and reprogramming costs for nanobots. "
    },
    {
        "title": "[Vestigial] OrbitLink Communications",
        "Summary": "OrbitLink Communications was established when the Alexandriat Space Settlement was under construction to augment standard communications channels. This was following a Foundation society survey that showed that the key factor putting people off of moving to their new settlements was the lack of access to YouTube. ",
        "Details": "Individuals who insist on transmitting and receiving data-hogging video and interactive real-time data with Earth-based services do so by paying exorbitant fees to OrbitLink. The company has made arrangements to place one of its antennas and dedicated fibre optics links on every Foundation Society settlement at zero cost, however transmissions through it are charged per byte. It is, therefore, unsustainable for primary communications. "
    },
    {
        "title": "Personal PCBs",
        "Summary": "Established in 2029 by Thomas Tezla, Personal PCBs supported some of the earliest ventures of the Foundation Society and market themselves as the solar system\u2019s finest custom electronics manufacturer. Upon construction of Bellevistat they were given a complimentary fabrication plant there to allow them to be closer to their end users reducing transport costs. ",
        "Details": "Personal PCBs manufacture pretty much any electronic device using a large variety of consumer and professional chips based on RISC-V instruction set, and their open source derivatives.Using material gained from asteroid mining, their electronics have prices comparable to custom electronics found on earth. All their electronics have a 4 year warranty (dependent on proof of shielding and good power regulation) and are shock and acceleration resistant. "
    },
    {
        "title": "Vigilant Systems",
        "Summary": "Vigilant Systems was formed by the merger Vigilant Sensors and Syst\u00e8mes de Purification in Q3 of 2030. They combined the expertise of Vigilant Sensors in chemical detection with the work of Syst\u00e8mes de Purification in earth based air purification to produce a leading expert in atmospheric regulation, which rapidly gained a foothold in many major space settlements. ",
        "Details": "Vigilant Systems supplies atmospheric and water supply monitoring equipment that reliably and accurately detects chemical concentration changes. These sensors provide a serial data output and list all elements detected and their relative proportions. They provide two variants for their systems: passive and XRF.The passive systems draw 0.5 W per sensor and output data in a constant stream with detection lower bound equivalent to 1,000 ppm and an accuracy of \u00b1100 ppm for a cost of $100 per sensor. The passive sensor may only be used on fluid material and has a temperature range of 223-573K. The passive sensor is vulnerable to radiation and amounts in excess of 50,000 Becquerels may cause inaccurate results from sensors.The XRF system draws 2,000 W during its triggered 10 second run time on a discrete sample of substance. This provides a detection lower bound of 50 ppb with an accuracy of \u00b110 ppb, however the sample is irradiated and made hazardous. This system costs $20,000 per unit and must be triggered to operate when a sample is in place. The XRF system may be used on matter in any form. "
    },
    {
        "title": "arno enterprises",
        "Summary": "\u00a0In 2043, DaVinci Meccanica won their first contract with the Foundation Society to build Alaskol, the first Big City on Luna. DaVinci Meccanica used this opportunity to finally test out their new product ARNO \u2013 a modular electronic platform, designed with the aim of\u00a0 increasing reusability.\u00a0The success of ARNO onboard Alaskol prompted DaVinci Meccanica to further explore into the incorporation of modular and repurposed devices within their design plans, with a specific focus on the integration of a variety of wearable devices for the residents onboard their settlements. ",
        "Details": "ARNO modules may be designed to customer specification and are designed to fit within any standard clothing or accessory, provided the volume exceeds 3cm^3. Customers are required to detail the form factor with engineering drawings, including detailing the available enclosed volume within which to fit the electronics. Modules come at a cost of $1000 each, although a 5% reduction is offered if more than 25 identical modules are purchased, and 10% if more than 50 identical modules are purchased. "
    },
    {
        "title": "space kettle",
        "Summary": "While all the large-scale space companies were busy developing the spacecraft that would finally enable commercial spaceflight to become a reality, they overlooked one small thing \u2013 kettles. Ok well actually not just kettles, but also all sorts of other appliances and items, from kitchen appliances to in flight entertainment systems. That is where Space Kettle comes in! Space Kettle\u2019s is a collaborative public database of designs that allow regular earth appliances to function as usual\u00a0 in space settlements, despite significantly different gravity, radiation and pressure conditions the will experience by pulling the solution to your design problem from a collaborative public database, Space Kettle helps to ensure lower cost and quicker development than trying to create all of these essential devices on your own.Unlike other Subcontractors, Space Kettle is also a real-world organisation, founded by previous UKSDC competitors. They work in partnership with the Space Science and Engineering Foundation and the UKSDC and are looking for students to get involved and submit their own designs to their design database, with the best designs getting the chance to feature here as part of this subcontractor. For more information please check out Space Kettle. ",
        "Details": "Space Kettle has designs for all of your potential space appliance needs, be it microgravity kettles or radiation-proof ovens. Due to Space Kettle\u2019s partnership with ElectroProtect, all appliances come built in with sufficient radiation shielding for standard operations within the solar system, although they are still unable to survive major solar flares and coronal mass ejections. Due to this longstanding partnership, standard Space Kettle appliances have managed to reduce costs to a level comparable with high-end appliances available on earth (use Miele appliances as a benchmark where available). However, for more niche applications, Space Kettle will also offer additional customisation packages for their appliances to deal with other challenges they may face in space.\u00a0Firstly, for operations in environments with an atmospheric oxygen percentage exceeding 30%, appliances will require additional features to make them fire-safe, which comes at an additional 50% cost to the customer. For operations in an atmosphere with a total pressure below 0.2 Earth atmospheres, this additional cost rises from 50% to 100% on top of Space Kettle\u2019s standard price, as the appliances must be made air-tight and pressurized.Secondly, Space Kettle offers the option of devices which can operate outside of standard Earth gravity conditions. For devices that must operate in environments between 0.25 and 0.5g, this additional cost is only 25% on top of the standard appliance price, although this rises to a 50% additional cost for operations in environments below 0.25g. "
    },
    {
        "title": "Nitrogen-Hydro",
        "Summary": "With the advent of major space Settlements in the 2030s and 2040s, a gap in the market for life sustaining gases appeared. Just like the gases they supply, Nitrogen-Hydro rapidly expanded to fill this available space in the market. The company also sells its flagship product, water, which is marketed as; \u201cNever having been touched by human pollution, free from additives and contamination.\u201d ",
        "Details": "Nitrogen-Hydro ships nitrogen, oxygen, and clean water from its facilities. Liquid nitrogen and water are shipped in sealed CASSSC\u2019s from their production facilities at Alaskol and Argonom.Liquid nitrogen is priced at $0.15 per litre, liquid oxygen at $1.5 per litre, while the flagship product, water, is priced $5 per litre. "
    },
    {
        "title": "Effective Disposal Solutions",
        "Summary": "Effective Disposal Solutions offers a final disposal service for irreducible waste products out of internal reprocessing systems. This includes dealing with hazardous waste such as spent nuclear fission fuel. Ultimate disposal involves questionable ethical decisions in the name of capitalism; these involve burying waste on areas of moons currently devoid of human habitation, or using reentry conditions to sublimate or autoclave certain materials. ",
        "Details": "\u00a0Effective Disposal Solutions charge by the mass of the material to be disposed of, charging $5,000 per kg, requiring the waste to be delivered to their facilities in lunar orbit. Due to the high demand for their services, they limit the use of their services for a single client to 2,000 kg a year. "
    },
    {
        "title": "Extreme Survival Technologies",
        "Summary": "Following a suit leak only 30 seconds in to his first space walk, founder Liam McDonnell was appalled by the low quality and safety standards of other privately sold space suits on the market. This led him to build up a team of experts from around the globe to design higher quality garments to ensure the safety of those wearing them. ",
        "Details": "Extreme Survival Technologies (EST) build spacesuits, and pressurised fabric furniture and impact protection systems (e.g. airbags and restraints) from its Alaskol facility. Its series of custom inflatable products are not rated for extravehicular use but cost only $500 dollars per m3 enclosed.EST\u2019s most popular products are its spacesuits however, with the most popular model being a hard shell suit customised for lunar operations but frequently used for other applications. Efficiencies of line production enable $9,000 unit costs. They are particularly well designed to deal with the dust of lunar and Martian operations.\u00a0Corporate Links:EST offer a substantial cost reduction on their products to Condor in thanks for the latter\u2019s zero-cost patent-licensing scheme which has allowed EST to use their dust-tolerant seal designs. Condor are able to quote a 20% saving on EST products thanks to this relationship. "
    },
    {
        "title": "Lossless Airlocks",
        "Summary": "Based out of Los Angeles, Lossless Airlocks was founded by American Entrepreneur Aleksey Cochrane, who started out as a private submarine designer, before catching the space bug during the major TV coverage of the construction of Liberty Space station and transitioning his expertise to space airlock construction. ",
        "Details": "Lossless Airlocks (LA) has developed and sells airlocks and hatches that operate with almost no loss of atmosphere to space on opening. LA offers systems in several designs and sizes. These comprise their cylindrical airlocks, which come in various sizes for different purposes, and their hatches, which provide interfaces between already pressurised volumes. The end closures form a flat covering that slides to open the chamber.The cylinders may be attached at either end of the cylinder (behind the door mechanism) or at the centre of its length. The hole for the airlock in a pressurised hull will induces a region where the local stress in the material is three times higher than the unaltered hull.The airlocks available are for a single occupant, up to three occupants, up to ten occupants, and one capable of passing a single CASSSC. The external dimensions of these cylinders are \u00d81.5 m by 2.2 m, \u00d83 m by 3.2 m, \u00d84.5 m by 5 m, and \u00d87.5 m by 11.5 m respectively. The diameter of the internal chamber is 95% of the external diameter. The prices for each of the airlocks are $6,000, $20,000, $60,000, and $160,000 in order of increasing size.LA produces hatches for joining pressurised volumes in the same diameters as its airlocks as well as a specialist component to allow docking with front of a pressurised CASSSC. These hatches cost one quarter of the equivalent airlock price and $40,000 for the specialist CASSSC model. Prices do not include shipping from Alexandriat.\u00a0Corporate Links:Lossless Airlocks are jointly owned by Condor and they share production facilities, enabling cost savings during integration and design. Condor may quote a 20% saving on LA products to the Foundation Society (in fact, the saving is more substantial than this). "
    },
    {
        "title": "Aesculapian Ventures",
        "Summary": "Aesculapian Ventures is a medical organization who manufacture medical supplies and equipment for use in cislunar space. From their home at Liberty they are at the cutting edge of medicine, being able to construct advanced artificial organs for use in humans.  ",
        "Details": "Their main business is managing a series of hospitals and hospices in LEO, but they sell 3D printers that can manufacture artificial organs for use in settlements for $50,000,000 each. They also act as the main manufacturer and supplier for all settlements in cislunar space and beyond for more mundane medical and pharmaceutical supplies. "
    },
    {
        "title": "CRISPR Cod",
        "Summary": "CRISPR Cod sell, despite their name, a large variety of genetically modified fish from their base at Liberty. Established by a group of fishermen from the Scottish Highlands, this company has long been researching genetic modification in order to increase fish yields. As such they had the necessary expertise to adapt their fish to survive and thrive in all gravitational environments up to 1g, perfect for the rapid expansion of space settlements. ",
        "Details": "CRISPR Cod sells its fish eggs at a competitive average price of $500 per 1kg(~3,000 eggs), presuming safe transportation, the fish are guaranteed to provide greater yields of produce with greater resistance to parasites and diseases.In efforts to curb the potency of the release of any genetically modified organisms into the greater environment, each fish has had its reproductivity slightly diminished, meaning that a colony of fish will decrease slightly with each generation requiring a regular top up of eggs. "
    },
    {
        "title": "Modular Ecology",
        "Summary": "CEO Dana Williams has always had a bit of a green thumb. With her first vegetable\u00a0patch at only 3 years old, she has always loved the knowledge that so much of her food had been grown in her own back garden. She founded Modular Ecology in 2034 to allow those going into space to have this same opportunity.  ",
        "Details": "Modular Ecology manufactures potable hydroponic and aeroponic ecosystems at Alexandriat for sustaining long duration spaceship crews. The modules attach to the exterior of a ship, over an airlock that would normally go to vacuum. New inter-orbit spacecraft are designed with appropriate interfaces as standard.Use of a Modular Ecology system requires that two crew members be trained to work the farm for one hour per day on average, mostly to harvest food for each day\u2019s meals from chicken-based or agricultural systems. These deliver grains, vegetables, fruit, meat and eggs. The systems require bi-annual maintenance to replenish water and nutrients, introduce non-inbred animals, and replace plant species that have died off.Sizes are available for crews of five ($3,000,000), eight ($4,000,000), and twelve ($5,000,000) while special orders are reactively fulfilled. Specialised installations for more than 1000 people can be ordered for $75,000 per person plus a base charge of $12,000,000. "
    },
    {
        "title": "Svalbard Seeds",
        "Summary": "Svalbard Seeds have expanded their mission to catalogue and store the genetic information of all plants, as well as to provide seeds to anyone wishing to purchase them. Originally based in Svalbard, Sweden, they have since moved their base of operations to Argonom and have constructed the solar system\u2019s largest seed vault there, with the hope to spread natural plants to all corners of the solar system. ",
        "Details": "Svalbard seeds sell all types of seed and cutting at a price of $1 dollar per 100 seeds or cuttings. It is required that these seeds be transported in refrigerated containers to prevent them from germinating before being planted. Customers are also informed that it is standard for around 50% of seeds not to grow properly, and so to order appropriately. "
    },
    {
        "title": "Synthetic Seeds",
        "Summary": "Synthetic Seeds are based in Lunar orbit and have used their extreme remoteness to render any restrictions on genetically modified organisms redundant, allowing for far greater experimentation into seed modification. They are famed for their web portal, offering consumers the ability to customise the taste of the produce grown, along with almost all aspects of each plant\u2019s genetics.  ",
        "Details": "They manufacture genetically modified plants with efficiencies that are getting close to the theoretical maximum of 11%. In ideal scenarios this leads to a doubling of growth rates, a doubling of yields, a lesser need for resources, and complete immunity to any known parasite or disease.However, their enhanced reproductivity has meant that on Foundation Society settlements, areas dedicated to farming these seeds require full automation, with separate atmosphere processing and additional measures to ensure that no seeds are released into the greater environment.Prices are on average $1 per seed, with other offerings such as infertile trees saplings that can mature in as little as 5 years priced at $100 dollars per sapling. "
    },
    {
        "title": "Aldrin Orbitals",
        "Summary": "Aldrin Orbitals is an offshoot management company of the Foundation Society, created to operate the Aldrin Cycler, Benevectoras. Benevectoras is advertised as the safest and cheapest way to travel between the two planets, and offers many luxuries often not found on interplanetary spacecraft for the voyage, including a swimming pool. ",
        "Details": "Aldrin Orbitals allow for the transport of passengers between Earth and Mars and vice versa. They specifically operate between the space ports of Columbiat and Aresam.Benevectoras is actually 6 separate spacecraft, allowing transfers from Earth to Mars and Mars to Earth almost every 8 months. One-way tickets cost $700 per day for the 146 day transit. "
    },
    {
        "title": "Custom Cargo Accommodations",
        "Summary": "Custom Cargo Accommodations (CCA) produces Cargo Accommodation Standard Space Shipping Containers (CASSSCs), compatible with standard interfaces on all launch vehicles and interorbital spacecraft currently in use. Taking inspiration from the shipping industry on earth, the Foundation Society decided in 2038 that all extraterrestrial cargo must be transported in CASSSCs.  ",
        "Details": "CASSSCs are 9 metres long with square 4.5 metre cross-sections and weigh 1 metric tonnes each when empty. Generic CASSSCs are aluminium, fully enclosed and vented to permit pressure equalisation, however special CASSSC\u2019s can be whatever customers choose within standard size and interface constraints, including pressurised, open framework or made of composite materials. CASSSCs, thanks to Foundation Society backing, are now available from distribution facilities at all major Foundation Society settlements and transportation hubs.Each CASSSC costs $2,000 for hire, presuming return to a facility for refurbishment, or $12,000 for the full purchase of one. "
    },
    {
        "title": "Consegna Veloce",
        "Summary": "Consegna Veloce operates interplanetary charter vehicles for either cargo or passenger transportation. Their crewed spacecraft called Caroliners, named after their late founder Carola Genovese. ",
        "Details": "Caroliners can carry payloads of up to 120,000 kg or up to 30 passengers, and can travel to and from almost anywhere in orbit within the inner solar system. In order to reduce radiation exposure, and to increase shipment times as well, Caroliners are designed to engage longer burns, reducing the transit times between destinations to around half that of a typical Hohmann transfer.They charge either $15.54 per tonne per m/s of delta v for cargo or $1,200 per day of travel for passengers. "
    },
    {
        "title": "Custom Courriers",
        "Summary": "Maisie Watson started out as a humble postie from the West Midlands before she decided to found Confirmed Couriers in 2037. She realised that their had to be a better way to track deliveries and ensure that all customers received\u00a0their parcels safely and in a timely manner. Using her experience as a postie, she rapidly expanded the business to handle tracking of almost 1/4 of all earth based parcels, before expanding the companies\u2019 ventures into space in 2041. ",
        "Details": "Confirmed Couriers has a large number of offices in all major settlements and transport hubs from where they track and manage the transfer of cargo for their clients. They have negotiated with the Foundation Society an agreement for the tracking of cargo for settlement construction and operations in cislunar space.Confirmed Couriers charge $350 per CASSSC for the tracking of the cargo, as well as managing the transfer of cargo between carriers at each stage on its journey. All cargo must be signed off and confirmed as delivered by the recipient, to ensure all parcels reach their destination safely. "
    },
    {
        "title": "Dangerous Packages",
        "Summary": "Dangerous Packages emerged as an offshoot from the now inactive Vulture Aviation, and now acts as an independent firm with regular contracts with almost every major space settlement. Their company motto is; \u201cIf no one else will take it, we will.\u201d ",
        "Details": "Dangerous Packages is a transportation company that specialises in the controversial movement of hazardous material from one location to another. This includes the nuclear material that is used in nuclear fission power generation.Based at Alexandriat, their spacecraft are crewed, and charge $25,000 a day for the transportation of up to 5,000 kg of hazardous material to anywhere in orbit in the inner solar system. "
    },
    {
        "title": "Earhart-VALIANT",
        "Summary": "Earhart-VALIANT In 2030, EAI acquired the launch service provide\u00a0VALIANT, that company becoming Earhart-VALIANT.\u00a0Earhart-VALIANT operates two classes of vehicles,\u00a0Aquila\u00a0and\u00a0Grypus. The small Aquila vehicle, originally developed to support lunar mining, hold the distinctions of being the most-launched platform on Earth. ",
        "Details": "The Aquila launch vehicle can lift 100 metric tonnes into orbit for a price of $5,000,000 per launch from Earth into anywhere within Low Earth Orbit, with this capacity being reduced to 80 tonnes for launches to L1.The Grypus rocket is able to carry 225 tonnes into Low Earth Orbit and 200 to L1, although come at the cost of $11,000,000 per flight. Due to Earhart-VALIANT\u2019s ongoing campaign to reduce climate impact, neither vehicle may be launched in an expendable configuration, instead imposing the requirement that the vehicle return to launch site in all cases. "
    },
    {
        "title": "Frozen Freightage",
        "Summary": "Frozen Freightage do their best to provide refrigerated CASSSCs for almost any kind of cargo, be that transport of foodstuffs, chemicals or biological samples. However, perhaps their most famous CASSSC is the walk in wine cellar owned by founder and CEO Jacques Boudon which is rumoured to travel with him at all times. ",
        "Details": "Frozen Freightage modifies special order CASSSCs with equipment to allow for the pressurised, isothermal, and sterile transportation of special requirements cargo. These heavily specialised CASSSCs require a near constant power source, usually running off the spacecraft\u2019s electrical system, and have all their thermal insulation and cooling built in.The equipment and insulation to keep cargo at a specified constant temperature anywhere between 120K and 290K takes up space inside the CASSSC, reducing the usable volume to 5 metres long with a 2 metre square cross section. The empty mass of the CASSSC has also been increased to 10 metric tonnes.They buy and then modify CASSSCs at Alexandriat, selling them on for $90,000 each.\u00a0 "
    },
    {
        "title": "Interorbital Heavy Payload Carriers",
        "Summary": "Interorbital Heavy Payload Carriers (IHPC) is a Danish company and operates a fleet of gargantuan spacecraft which are some of the largest in current usage. With a volume equivalent to over 2000 blue whales, these vehicles are an impressive sight to behold. ",
        "Details": "A single IHPC craft can move over 1000 fully loaded CASSSCs at once to almost anywhere in the inner solar system through the use of efficient Hohmann transfers. These massive ships offer some of the lowest cargo fees of any transportation company, coming in at $3.95 per tonne per m/s of Delta V. The customer must make the necessary calculations of Delta V and account for the transport mass when booking cargo space on the ship.Their spacecraft, due to their size, cannot dock with settlements and require specialist portside equipment that is only available at certain spaceports (Columbiat, Aresam, and Astoria) or require tugs to collect delivered CASSSCs from free space. "
    },
    {
        "title": "Condor MFR",
        "Summary": "Condor MFR The Multi-Fuel Rocket is a system that we\u2019re very proud of; providing heavy-lift capacity at 15% lower carbon emissions than others in field! How do we do it? That would spoil the magic! All we\u2019ll say is that we have some of the best chemical engineers in the game who specialise in the enrichment of bio-fuels to increase their power density, and we\u2019re very good at modelling solid particulates in combustion mixtures. ",
        "Details": "The Condor MFR launches out of the Republic of Nauru, an island nation lying very close to the equator, in order to maximise the vehicle\u2019s lift capacity. As such, the Condor MFR is able to lift 150 tonnes into Low Earth Orbit at a price of only $7,000,000 per launch due to their cheap, but effective, manufacturing methods of bio-fuels. "
    },
    {
        "title": "OMTC Nix",
        "Summary": "OMTC Nix With the completion of the Nix Space Elevator in the caldera of Ascreaus Mons, OMTC Nix now handles 85% of transport on and off Mars, with vast reductions in transport costs. The first became operational in 2064, helping with the construction of Argonom, which is located only 2km away and contains the cargo management facilities to support elevator operation. The settlement is held in a stacked orbit through the use of a solar sail to facilitate its operation, an idea first proposed by Dr. Robert Forward way back in the 1980s. ",
        "Details": "The OMTC Nix Space Elevator has revolutionised cargo transport within the Martian system with its ability to transfer over 1000 CASSSCs an hour between an orbit of 10,000km and the surface of Mars. For a fee of only $5 per CASSSC, cargo may be transfered down to the surface and handled by the Argonom facilities ready for use or further distribution. Transport from the surface to the orbiting distribution centre comes at a cost of $20 per CASSSC. "
    },
    {
        "title": "OMTC Transport Services",
        "Summary": "OMTC Transport Services OMTC owns over 70 cargo handling settlements within the solar system and moves over 1Mt around the solar system every day. With a company motto of \u2018Perfection Every Time\u2019, it is easy to see why so many people choose our services for solar system cargo transport. ",
        "Details": "OMTC Transport Services is a branch of Olympus Mons Trading Company, responsible for managing all the transport operations we are involved in. Due to logistical efficiency, we are able to reduce transfer costs of all cargo we handle by 2% for our customers, charging a flat fee of $2,500,000 for this service per project. We do not currently have the facilities to handle IHPC vehicles though and so these reductions do not apply to IHPCs. "
    },
    {
        "title": "SpaceTrans Inc",
        "Summary": "SpaceTrans Inc. started as a business plan written for a college class project by an ambitious self-styled entrepreneur who idolised the founder of Federal Express. The company managed to acquire funding to develop in orbit spacecraft construction facilities and nowadays they oversee, from their headquarters at Columbiat, over 50% of trans-orbit flights each day in cislunar space.  ",
        "Details": "SpaceTrans Inc can provide regular but unscheduled transportation services between locations in Earth orbit, including space stations, major commercial sites and future settlements. Rates average $2,000 per person and/or $50 per kg of cargo, per day of travel. "
    }
]

const options = {
    includeScore: true,
    keys: ["title", "Details"]
}

search = () => {
    // event.preventDefault();
    input = $("#searchbox").val();
    console.log(input);
    const fuse = new Fuse(data, options)
    results = fuse.search(input)
    console.log(results);
    $("#results-list").html(results.map((i) => `<li class="list-group-item"><div class="fw-bold">${i.item.title}</div><br> ${i.item.Details}</li>`));
}